### ISSUE TITLE
defer, %defer, and ?defer

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#110]
- [x] `defer expr`, evaluates expr when control flow leaves scope
- [x] `%defer expr`, evaluates expr when control flow leaves scope by returning an error from the function
- [x] `?defer expr`, evaluates expr when control flow leaves scope by returning null from the function
- [x] defer valid at statement level only in parser
- [ ] error when there is a defer with 0 block exit paths
- [x] make the returns respect defer
- [x] error when there is a `%return` in a function with void return type
- [x] optimization where the node remembers if it was error wrapped from a payload, if that is returned, then we know it is not an error. when `%return` returns it is for sure an error. otherwise we have to do a runtime check to find out if it's an error and then do the defer expression
- [ ] better defer implementation - instead of duplicating the code at every exit path, make a basic block that exit paths point to.
- [ ] error for control flow inside an expression exiting the defer expression scope? for example you probably shouldn't be able to `return` in a defer.

**Comment by SirCmpwn** [comment]
Not sure how it would take shape, but it would be nice to be able to assign and defer in one go (sugar wise). Something to this effect:

```
const foo %defer deallocate_foo(foo) = %return try_to_foo();
```

Further sugared:

```
const foo %defer deallocate_foo = %return try_to_foo();
```

With the implication being that deallocate_foo just takes one parameter that is foo.

**Comment by andrewrk** [comment]
The point of this syntax is so that the deallocation becomes "attached" to the allocation and you can't accidentally separate them. Is that right?

**Comment by SirCmpwn** [comment]
No, it's just sugar to make it so you can write less code.

**Comment by andrewrk** [comment]
Moved to individual issues.
