### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [andrewrk/zig#116]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/andrewrk/zig/blob/e18170ee0bf32996635397e8e919a14a21c88b56/src/main.cpp#L51 "main() function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "Uncaught exceptions") like they are described by Danny Kalev?

**Comment by kiljacken** [comment]
I'm not @andrewrk, but AFAIK know he uses a rather C-style C++, which among other thing mean that he does not raise any exceptions himself. I cannot say if he uses part of the c++stdlib that would raise any exceptions, or whether the LLVM C++ api does so.
So basically, he doesn't catch any exception because he doesn't use any exceptions :)

**Comment by elfring** [comment]
How would you like to take for a C++ exception like [std::bad_alloc](http://en.cppreference.com/w/cpp/memory/new/bad_alloc "Allocation failure")?

**Comment by kiljacken** [comment]
As I'm not really a C++ guy I can't be sure of this, but Andrew uses the libc malloc (here: [src/util.hpp#L32](https://github.com/andrewrk/zig/blob/e411467e1dd4557bb11698f2a5d979dfcbaea444/src/util.hpp#L32)) and I would not think that it throws a bad_alloc exception.

**Comment by andrewrk** [comment]
we compile with -fno-exceptions and panic if memory allocation fails, and then never free any memory ever.

I'm not interested in improving this aspect of the C++ code; I'm interested in improving the zig language and then rewriting the compiler with proper error handling zig style.
