### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [andrewrk/zig#117]
Would you like to [add more error handling for return values](https://github.com/andrewrk/zig/blob/ec33e5a638b816ab0ba1e4dd3f9433dbb71d7e53/src/ast_render.cpp#L197 "Update candidate: ast_print()") from calls of [the function "fprintf"](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output")?

**Comment by andrewrk** [comment]
You're not being helpful.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible?
