### ISSUE TITLE
expose environment variables via standard library

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#118]
as @sanxiyn pointed out, this line is incorrect:

``` zig
    env = asm("lea 0x10(%%rsp,%%rdi,8), %[env]": [env] "=r" (-> &&u8));
```
- [ ] expose environment variables via standard library
- [ ] add test to make sure it works

**Comment by sanxiyn** [comment]
The particular line is now fixed in bootstrap.zig.
