### ISSUE TITLE
slightly different error handling (long)

### ISSUE THREAD

**Issue by PavelVozenilek** [andrewrk/zig#122]
Some time ago I proposed error handling quite similar to what zig does, for a different language.  I am copying it here as an inspiration. Syntax is zig-like.

-----------------------

(1) Errors are defined like in zig. They are just symbols with numeric value. 0 means no error

-----------------------

(2) Normal functions with no errors:

    fn foo() { }
    fn bar() -> i32 { return 1; }

No suprise here.

-----------------------

(3) Function which may return an error just do it, without need for any annotation or special type or anything. 

The compiler knows that the function may also return error and this is important. Internally it would probably generate some union type.

    fn foo() 
    {  
      if (...) return MyError; 
    }

    fn bar() -> i32 
    { 
      if (...) 
        return 1; 
      else 
        return YourError; 
    }

Errors can be easily added or removed from the function, one local change is enough. 

-----------------------
(4) Returned error **must** be handled.

The compiler knows what called function may return and ensures that every error gets handled and only those which may happen are handled.

    fn bar() 
    { 
      if (...) 
        return MyError; 
      }
      if (...) {
        return YourError; 
      }
      ...
    }

    bar(); // error returning function invoked
    //
    // all possible errors must be handled now
    // otherwise it won't compile
    
    // 'err' is pseudo variable imitating global errno. 
    // Actual implementation may be different. 
    // When function returns proper value 'err' is set to 0.
    //
    if (err) {  
      // here we ignore all possible errors, 
      // it is something as catch (...) {}
    }

    bar(); // another call
    // Here every possible error is handled explicitly.
    //
    // If I omit any error it won't compile.
    //
    // If I try to handle something what cannot happen it won't compile
    //
    if (err == MyError) {
      ...
    } elif (err == YourError) {
      ...
    }

-----------------------

(5) Regular return value cannot be used until errors are handled

Compiler will ensure this.

    fn foo() -> i32 {
      if (...) {
        return MyError;
      }
      if (...) {
        return YourError;
      }
      return 1;
    }

    var x1 = foo();
    // will NOT compile, error handling is missing, 
    // x1 may not be defined at this point
    if (x1 > 0)  { ... }

    var x2 = foo();
    if (err) {
      return SomeError;
    }
    x2 = x2 + 1; // OK, at this point all errors were handled

    var x3 = foo();
    if (err) {
      x3 = 100; // I set value for the undefined x3
    } 
    x3 = x3 + 1; // OK, at this point x3 is always well defined

    var x4 = foo();
    if (err) {
       // empty body here
    } 
    x4 = x4 + 1; // will NOT compile, x4 may still be undefined

    var x5 = foo();
    if (err) {
       // here I CANNOT use x5
       ...
    } else {
      // here x5 is valid
      x5 = x5 + 1;
    }

-----------------------

(6) Trying to do error handling where it is not needed stops compilation.

    fn foo() { } // no errors

    foo();
    if (err) { } // will NOT compile, no error can happen at this point

-----------------------

(7) Errors can be passed up transparently.

    fn foo() -> i32 {
      if (...) {
        return MyError;
      }
      if (...) {
        return YourError;
      }
      return 1;
    }

    var x = foo();
    if (err) { 
      return err; // pass any error up
    }
    if (...) { 
      return YetAnotherError;  // add own error
    }

-----------------------

(8) When one is absolutely sure error cannot happen here and now it may be ignored explicitly.

    var x = (no-err)foo();
    x = x + 1; // OK

The compiler may use this as optimization hint. Will take the old ```foo```, remove all code related to errors and generate new, slim a fast alternative, and then invoke it from here.

Only certain error(s) may be known not to happen here. 

    var x = foo();
    assert(err != MyError); // compiler understands semantics, will check MyError is corrent here
    if (err == YourError)  { 
      // other errors still need to be handled
      ... 
    }

This, too, may be used as optimization hint.

-----------------------

(9) Advanced error handling

Whole block of code may be handled in one place.

    {
      // it feels as if no error handling is here
      var x = foo() + bar();
      x = x + 1;
      x = baz(x);
    }
    // But here we go. When the first error occurs in the previous block 
    // it will jump right here. It is little bit like C++ exception.
    if (err) {
      // must handle foo, bar and baz errors
      ....
    }

-----------------------

(10) Even more advanced error handling. (I am not sure whether this is (easily) implementable.) 

Postponed error handling can possibly be extended to complete functions. They would look as if no error can happen but secretly would pass any that occurs up. All errors have to be caught, at worst in ```main()```.

This would be similar to effects in language Nim, or similar to checked exceptions in Java but w/o the need to annotate every function.

    foo() { 
      if (...) return MyError;
    }

    bar() {
      if (...) return YourError;
      foo();
    }
  
    baz() {
      if (...) return OurError;
      bar();
    }

    baz();
    if (err) {
      // handle foo, bar and baz errors
      ...
    } 

-----------------------

(11)  When there are several function calls in one expression.

    var x = foo() + bar();
    if (err) {
       // handle errors from both foo and bar
    }

    // Here execution will stop at the first error
    foo().bar().baz();
    if (err) {
      // handle foo, bar and baz errors
      ...
    }

-----------------------

(12) What if single symbol for error is not enough?

If error needs to pass additional data it would be up to the programmer to implement it and to make sure it is all OK.  

This should keep compiler simple while still covering vast majority of use cases.

-----------------------

(13) What are the advantages of this approach?

1. Simplicity. No funny annotations, no special types needed.
2. Easier to refactor due to above.
3. Compiler doesn't allow errors to disappear, doesn't allow unused code.
4. The code looks as if written by very cautious C programmer.

**Comment by thejoshwolfe** [comment]
regarding (9), I'm a little bit scared by how non-obvious the conditional branches are in that code. I understand that many people see that as a positive thing, since the author doesn't need to worry about writing all the conditional branches in. However, if you were asked to analyze the possible execution paths of the code in (9), you would need to look at the definitions of the functions called to understand how execution might jump around.

But then even more subtly, if you don't have explicitly declared error returns, you need to actually scan the body of the functions you're calling to understand if the calling code might jump around after calling the function. Again, I get that this is all considered a positive feature by some, but it's not Zig's philosophy to generate hand-wavy "magic" code. Zig is about being able to look at code and know exactly what's going to happen at runtime, even if that means the author needs to be a little more verbose and the reader needs to process a little more information. Zig's philosophy is that the extra information is the real truth, so hiding it would only be making the code more confusing.

**Comment by PavelVozenilek** [comment]
@thejoshwolfe: (9) is like C++ exceptions. One needs to take lot of care not to leak or anything. I personally would be happier with handling after every call, but some may not. The (10) is even more ambitious. I put it in for completeness.


The actual errors may be listed by a hypothetical IDE. When compiler enforces their handling it should be easy. Code that is wrong (not handling/handling too much) will not compile. Reader should not be confused at any moment.

**Comment by PavelVozenilek** [comment]
Use of ```err``` pseudo-variable would allow single ```defer``` statement for successful and error exits.


    fn foo() 
    {
        defer if (err) { // here the err is error returned from this function
              ...
            } else {
              ...
            }
    
       return MyError;
    }

**Comment by andrewrk** [comment]
Zig's existing error handling accomplishes the goals stated here while having consistent expression syntax and straightforward logic.
