### ISSUE TITLE
Provide binaries for less experienced users.

### ISSUE THREAD

**Issue by oeb25** [andrewrk/zig#127]
As someone who is quite new to the entire c world, I haven't been able to build the binary, cmake is still a bit weird to me.

Would it be possible to create an easy to install version or guide, without the need of installing a specific version of LLVM and such?

If this is too much work I understand.

**Comment by andrewrk** [comment]
This is a perfectly reasonable thing to ask for. However since the project is still so young and changing so quickly, we don't have such resources available yet.

At the very least, binaries will be provided for releases.

**Comment by nc-x** [comment]
@andrewrk  
I am not sure since I never did it, but I think CI and build artifacts should be able to do the job.

**Comment by andrewrk** [comment]
We'll have binaries for each release, and after the first release, binaries provided by a CI service.
