### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by xyproto** [andrewrk/zig#175]
Please tag with a version number (`0.0` or `0.1-rc` perhaps?) to make it easier to create proper packages for Linux distros while waiting for the release milestone (looks better than locking to a git commit, which is the [current situation](https://aur.archlinux.org/packages/zig/)).

**Comment by kiljacken** [comment]
Afaik the language is not yet at a point where a release would make sense,
nor would creating packages for the compiler.

**Comment by xyproto** [comment]
OK, looking forward to the first release. :+1:
