### ISSUE TITLE
replace %% operator with something more pervasive

### ISSUE THREAD

**Issue by codygman** [andrewrk/zig#176]
This looks like a language C programmers could move to transparently... Almost.

In my experience C programmers have a disdain for symbols and are quick to judge me ones as "uh oh, an operator soup language".

Maybe you could use something like .? if %% is indeed a null coalescing operator as I understand it. This has the advantage of C# using it.

This language had great ideas without a lot of learning overhead, if hate to see it not get adopted because of a single symbol.

Don't take my word for it. Maybe we could be scientific and poll a large group of C programmers see what their preference would be.

This all of course presumes you really care about adoption, which from your design this far, it seems you very much do.

**Comment by andrewrk** [comment]
I'm open to suggestions. What is the proposed alternative here? Can you give code examples?

**Comment by malthe** [comment]
I think the `expr %% default` syntax is quite readable and certainly very useful, but I think the prefix shortcut – for `%% @unreachable()` – is less obvious. How about:
```c
const number = parseU64("1234", 10) %!
```
The exclamation character meaning something like: "Panic!"

**Comment by andrewrk** [comment]
Some ideas about `%%` prefix operator:

 * remove it
 * change to a post-fix operator like `%!`
 * push the problem into user-land

for example, a function like this would work:

```zig
fn unwrap(value: var) -> @typeOf(value %% @unreachable()) {
    return value %% @unreachable();
}
```

(this would be better if we supported inferred return value type)

One of the driving factors for this syntax is that we have to print to stderr/stdout a lot and we want to make it easy to assert that no error occurred when doing so.

```zig
%%io.stderr.printf("blah\n");
```

With a post-fix `%!` operator:

```zig
io.stderr.printf("blah\n") %!;
```

If we didn't have this operator, we could define an additional method that called the real one and unwrapped it, like:

```zig
io.stderr.checkedPrintf("blah\n");
```

And the `checkedPrintf` function would essentially do `printf(...) %% @unreachable()`. I can see people thinking this is quite ugly, but maybe this is less ugly than the `%%` prefix operator.

**Comment by malthe** [comment]
From reading Rust code it seems `unwrap()` comes up all the time.

That would be an argument against specialised wrappers such as `checkedPrintf`.

**Comment by raulgrell** [comment]
Just to note I too would prefer a postfix %! and ?!

For purely aesthetic reasons, and a general dislike for specialised wrappers.

**Comment by thejoshwolfe** [comment]
I'll throw in my `$0.02` about operator aesthetics. One advantage of a prefix operator instead of a postfix operator is that they'd all be vertically aligned. Consider:

```zig
fn prefix() {
    %%printf("Hello");
    %%printf("Hello World");
    %%printf("\n");
}
fn postfix() {
    printf("Hello") %!;
    printf("Hello World") %!;
    printf("\n") %!;
}
```

Vertical alignment is cool for a number of reasons. One is it's easier to read, as in the above. Another is that if you forget it, and have several functions in a row that need to assert no errors (like the above), you can use block-select mode in an editor to add the missing operator to all the lines at once. You don't get those advantages with a postfix operator.

But of course, this is sort of a minor issue, and there are arguments for having postfix operators too. Just wanted to show some examples.

Something else to note is that Zig currently has no unary postfix operators (and C only has `x++` and `x--`), so the proposed `x%!` and `x?!` would be unique.

**Comment by raulgrell** [comment]
Both the vertical alignment and lack of other unary postfix operators are good points. Also, consider the following. Prefix seems clearer

```
 fn prefix() {
    %%printf("{}", %%foo())
}
fn postfix() {
    printf("{}", foo() %!) %!;
}
```

**Comment by andrewrk** [comment]
Alright seems like we don't really have a better proposal than status quo. Still open to proposals, feel free to comment here or open new issues.
