### ISSUE TITLE
Test 164/165 fails

### ISSUE THREAD

**Issue by xyproto** [andrewrk/zig#184]
After compiling zig version 0.0.0 on 64-bit Arch Linux, and running the `./run_tests` executable, I get:

```
...
Test 164/165 self hosted tests (debug)...
Self-hosted tests failed:
./zig test ../test/self_hosted.zig
unable to open '../test/self_hosted.zig': file not found
```

Zig is built with these commands:

```bash
  mkdir -p build
  cd build
  cmake "../$pkgname" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DZIG_LIBC_LIB_DIR=$(dirname $(cc -print-file-name=crt1.o)) \
    -DZIG_LIBC_INCLUDE_DIR=$(echo -n | cc -E -x c - -v 2>&1 | grep -B1 "End of search list." | head -n1 | cut -c 2-) \
    -DZIG_LIBC_STATIC_LIB_DIR=$(dirname $(cc -print-file-name=crtbegin.o)) \
    -GNinja
  ninja
```

**Comment by andrewrk** [comment]
What directory are you running ./run_tests from? It's looking for ../test/self_hosted.zig. Does that exist?

**Comment by xyproto** [comment]
`./run_tests` is being run from the `build` directory. Here are the `build`, `check` and `package` functions currently in use in [this package](https://aur.archlinux.org/packages/zig/):

```bash
build() {
  mkdir -p build
  cd build
  cmake "../$pkgname" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DZIG_LIBC_LIB_DIR=$(dirname $(cc -print-file-name=crt1.o)) \
    -DZIG_LIBC_INCLUDE_DIR=$(echo -n | cc -E -x c - -v 2>&1 | grep -B1 "End of search list." | head -n1 | cut -c 2-) \
    -DZIG_LIBC_STATIC_LIB_DIR=$(dirname $(cc -print-file-name=crtbegin.o)) \
    -GNinja
  ninja
}

check() {
  cd build

  ./run_tests || true # test 164 of 165 fails: https://github.com/andrewrk/zig/issues/184
}

package() {
  DESTDIR="$pkgdir" ninja -C build install
  install -Dm644 "$pkgname/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
```

**Comment by andrewrk** [comment]
Try running the install step before `./run_tests`, does that work?

Can you insert into your `check` function a debug line, maybe `file ../test/self_hosted.zig`.

**Comment by andrewrk** [comment]
I'll re-open if further information is provided.

**Comment by xyproto** [comment]
Sorry about the delay, I have been moving. The output from the `file` command is `../test/self_hosted.zig: cannot open `../test/self_hosted.zig' (No such file or directory)`.

**Comment by andrewrk** [comment]
I believe I just pushed a commit to fix this issue. Please let me know if it's still a problem.

**Comment by xyproto** [comment]
Thanks, that resolved the issue!
