### ISSUE TITLE
How are supposed libraries to be distributed in binary form?

### ISSUE THREAD

**Issue by aindigo** [andrewrk/zig#195]
If i want to distribute certain library in binary form (made with zig), I need to pass the definitions of my structs/functions in some way, and since zig has no replacement to header files, 
do I need to export an H file anyways and distribute that along my lib? no problem with that, unless i want to export an 'zig' idiomatic library (error / unions).

**Comment by andrewrk** [comment]
If you want to distribute in binary form, then you have to use the C interface, and you can target an object file, a static library, or a shared library.

So for example you would do something like

```zig
export fn add(a: c_int, b: c_int) -> c_int {
    return a + b;
}
```

Then Zig will export the binary (object, static lib, or shared lib) and generate an .h file.

Now, all that being said, the goal of distributing in binary form is code obfuscation (tell me if that is not correct).

Zig does not try to solve code obfuscation, at least yet, and I'm not convinced that Zig *should* try to solve code obfuscation.

The way that Zig libraries are intended to be reused is in source form. Package management isn't done yet, but the way it will work is with a list of package names along with a URL of how to obtain the package and a hash to verify that the thing downloaded is the same as expected.

**Comment by aindigo** [comment]
I understand that zig does not try to solve the obfuscation, but there is another problem with the distribution of libraries,maybe in this stage it does not matter but some licenses are viral ,if you, for example link statically against a library that is under LGPL (ie. libSDL) you have to open source your code. And i think it is important to not to depend or , at least, to have some option vs the C header file. but, i also just realised that you could simply distribute a .zig file along with your binary with exports to extern definitions of your functions in the library.

**Comment by andrewrk** [comment]
The rules for how the viral licenses works are not straightforward. For example, what if there is a `static inline` function in an .h file? Does that count as statically linking? There's a library called glm which is a header-only math library for 3d applications, which luckily is MIT licensed, but if it had one of these viral licenses, how would that work? That's a pretty close analogy of what it's like to use a zig library in source form.

To be clear, about C interface - exports which use the C interface have restrictions on what you can do. For example, an exported function is not allowed to have generics. An exported struct may not have any members. An exported enum must not have any types for any of the fields. And so on.

Point being, when you say:

> you could simply distribute a .zig file along with your binary with exports to extern definitions of your functions in the library.

I'm not sure exactly what you mean, but it doesn't sound like a viable strategy.

All that being said, we've now identified 2 reasons for distributing in binary form:

 * Code obfuscation
 * Conforming to license restrictions

Perhaps we could solve these problems independently, if at all. For example, one could annotate a library dependency as required to not link statically. In this situation the compiler could automatically transform the library into a shared library for the functions, while still doing generics, enums, and types correctly.

I'm not sure I'd want to go down this path - I'd rather see more liberal licenses be used - but perhaps if we did try to solve this, it would be an approach that more directly addressed the goals.

**Comment by thejoshwolfe** [comment]
https://www.gnu.org/licenses/gpl-faq.en.html#LGPLStaticVsDynamic

> If you statically link against an LGPL'd library, you must also provide your application in an object (not necessarily source) format, so that a user has the opportunity to modify the library and relink the application.

so you don't have to open source your code if you statically link against LGPL; you just have to allow the end user to swap out the LGPL part with a modified version and somehow let the user relink.

doesn't automatically solve the problem, but wanted to point out that static linking LGPL doesn't force you to be open source.

**Comment by aindigo** [comment]
thanks you @thejoshwolfe , nice to know, there are a lot of misconceptions about the matter.
