### ISSUE TITLE
instead of memberCount builtin, have it be a member of enum type

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#198]
Currently we have `@memberCount(enum_value)` to return the number of fields in an enum. Instead, let's have struct and enum types have a `len` field like array types that tell how many fields.

**Comment by thejoshwolfe** [comment]
so slices are like structs with a ptr and len field, but the len field doesn't refer to the number of fields, but rather has special meaning for slices? something seems wrong with this idea.

this would also mean you can't declare your own fields called len. not sure if that's good or bad.

**Comment by andrewrk** [comment]
Hmm good point, it conflicts with the user namespace. In that case we should probably stick with builtin function for this.

**Comment by jonathangjertsen** [comment]
In case someone else is updating very old zig code and got here trying to find out where `@memberCount` went: this is now spelled `@typeInfo(...).Enum.fields.len`

**Comment by andrewrk** [comment]
Wow that's quite an old version indeed. Welcome back!
