### ISSUE TITLE
Compiler gets stuck on nested refs

### ISSUE THREAD

**Issue by ofelas** [andrewrk/zig#200]
Compiler may get stuck (consuming cpu/memory) on potentially invalid code. Actually not sure what the correct Zig term would be. See `PROBLEM` in `n5` below.

```zig
pub fn n1(inline T: type) -> type {
    struct {
        left: &T,
        right: &T,

        const Self = n1(&T);
    }
}

// pub struct n2 {
//     links: n1(n2), // error: 'n2' depends on itself (even if it's a refs?)
// }

pub fn n3(inline T: type) -> type {
    struct {
        left: T,
        right: T,

        const Self = n3(T);
    }
}

pub const n4 = struct {
    links: n3(&n4), // compiles just fine
};

pub fn n5(inline T: type) -> type {
    struct {
        left: T,
        right: T,

        const Self = n5(&T);  // PROBLEM: compiler never comes back (ref to ref?)
    }
}

pub const n6 = struct {
    links: n5(&n6),
};
```

**Comment by andrewrk** [comment]
I'll look into this, but note that if you're trying to get a reference to your own type, you'll want something like `const Self = Foo(T)` rather than `const Self = Foo(&T)`.

**Comment by ofelas** [comment]
Yes, I know. Stumbled into it by mistake as I was changing from `&T` to `T` and forgot one.

**Comment by fsaintjacques** [comment]
What's the difference between:

```
struct A(T: type) {
}
```

and

```
struct B(inline T: type) {
}
```

Can `T` be given at runtime or is `T` implicitly inline if the keyword is missing?

**Comment by andrewrk** [comment]
Arguments of type `type` must be inline. I don't remember if I made it an error to omit `inline` or if the inline is implicit.

**Comment by fsaintjacques** [comment]
I guess it isn't:

https://github.com/andrewrk/zig/blob/master/std/list.zig#L6

**Comment by andrewrk** [comment]
That might change with #160

**Comment by andrewrk** [comment]
I think this is solved now.
