### ISSUE TITLE
internal compiler crash having to do with constant math

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#201]
```zig
const TINY_QUANTUM_SHIFT = 4;
const TINY_QUANTUM_SIZE = 1 << TINY_QUANTUM_SHIFT;

var block_aligned_stuff: usize = (4 + TINY_QUANTUM_SIZE) & ~(TINY_QUANTUM_SIZE - 1);
```

```
./zig build test.zig --name test --export obj --check-unused
```

**Comment by aindigo** [comment]
if I define the const variables with explicit types (or casting them) the crash goes away. I think the compiler should just inform you and fail gracefully with an error, since theres no way to imply a type there, and any assumption made can be very dangerous.

**Comment by andrewrk** [comment]
That's probably what it's supposed to do. I'll look into this in a bit.

**Comment by andrewrk** [comment]
This is fixed now. Problem was failing to make it be a compile error to do the `~` (binary not) operator on an integer literal.
