### ISSUE TITLE
Binary-not operation fails to compile only on global scope

### ISSUE THREAD

**Issue by aindigo** [andrewrk/zig#203]
This code compiles and passes the assert 

```
fn neg_test3() {
    @setFnTest(this, true);
    const TinyBlockSize : usize = 16;
    const NegTinyBlockSize : usize = ((32 + TinyBlockSize - 1) & ~(TinyBlockSize - 1)) >> 4;
    assert(NegTinyBlockSize == 0x2);
}
```

But if the same two variables are defined on global scope the compilation fails with the following error (it happens even if i declare them mutables):

```
./prefixes_test.zig:36:37: error: global variable initializer requires constant expression
const NegTinyBlockSize2 : usize = ((32 + TinyBlockSize2 - 1) & ~(TinyBlockSize2 - 1)) >> 4;
                                    ^
```

Im trying to solve this issue my self. but im trying to get familiar with the compiler code.

**Comment by andrewrk** [comment]
Here's a clue: https://github.com/andrewrk/zig/blob/a098c07aa77a48fe05de3bf2a11884c0dd0cfafb/src/analyze.cpp#L6225

Fair warning, I'm rewriting how constant evaluation works in the IR branch: https://github.com/andrewrk/zig/tree/ir

**Comment by aindigo** [comment]
thanks  @andrewrk  ill check the code of the compiler this weekend, in the meantime ill be trying finish my  implementation of the mmap allocator with walk-arounds and hardcoded values,
anyways,  to program a *kind of real* use case system have been really useful for me to get accustomed to the language and to discover tiny bugs, i have a couple , but first i need to find a pattern on how to reproduce them, is related with parenthesis and my chaotic way to code, mostly from C habits.

**Comment by andrewrk** [comment]
fixed after merging ir branch
