### ISSUE TITLE
zig usage is not compliant with standard usage string

### ISSUE THREAD

**Issue by fsaintjacques** [andrewrk/zig#207]
The following [code](https://github.com/andrewrk/zig/blob/master/src/main.cpp#L281-L289) mandates that `--name` and `--export` are provided. If they're required, they shouldn't be in the options section and be provided as arguments.

The solutions are:
- move said options to required arguments, e.g. `zip build <name> <export_type> <sources>...`
- provide default such that they can stay options (might be complicated with `--name` and multiple sources) and the user isn't forced to use them.

It creates initial churn when a new user types `zig build my_file.zig`.

**Comment by andrewrk** [comment]
Good call.

For some context, name and export used to be specified in the source code in a "root export" node. It was removed in f1d338194e9a00e56a42da1298f2ac0ed75797df.

In the future, I expect name and export type to be specified as part of the zig build system (see #204). So, for example, these values would be specified in build.zig and the actual command one would use in practice would be simply `zig build`.

However, the future is not yet here, and thus you are correct that we should make this change to reduce churn.
