### ISSUE TITLE
Explicit generics over parameterized generics

### ISSUE THREAD

**Issue by SirCmpwn** [andrewrk/zig#231]
Using a syntax for generics that's closer to other languages more closely matches expectations and is less ambiguous. Today:

```
fn max(comptime T: type, a: T, b: T) -> T { ... }
max(i8, 10, 20);
```

Better:

```
fn max<T>(a: T, b: T) -> T { ... }
max(10, 20); // T inferred, could also be explicit as max<i32>(10, 20);
```

**Comment by thejoshwolfe** [comment]
See https://github.com/andrewrk/zig/issues/151#issuecomment-256808723

There I'm discussing the switch from comptime parameters (then called "inline" parameters) being a separate list in parentheses to being intermixed with the runtime parameters. The topic of using angle brackets is also discussed.
