### ISSUE TITLE
Generalize |...| for user use

### ISSUE THREAD

**Issue by SirCmpwn** [andrewrk/zig#232]
Make the following equivalent:

```
map { things } |thing| { ... }
```

to this:

```
map({ things }, |thing| { ... })
```

Optimize builtins as appropriate. Note that since these are just expressions, the following should also work:

```
const things_times_two = map(things, |thing| thing * 2);
```

**Comment by andrewrk** [comment]
This is a big discussion. Can you add to this proposal with some elaboration, explanation of types, and some example use cases?

**Comment by SirCmpwn** [comment]
I don't understand exactly what you're asking for.

**Comment by andrewrk** [comment]
I want to understand your proposal better. As is, I don't really understand the suggestion. What is the type of `things`? What is the type of `thing`? Is `{ things }` an expression that results in `things`? Are you suggesting that we have an Iterable trait like Rust?

Help me see your vision for this feature.

**Comment by SirCmpwn** [comment]
things is just an array. An iterable trait would also be useful, but is tangential. Do you know how map works in other languages? It takes an array of things, invokes an expression (or function) for each one that returns a value, and creates a new array of the values returned. So:

```
const things_times_two = map things |thing| { thing * 2 };
```

Other use cases are other functional programming staples like fitler and reduce:

```
const things_gt_two = filter things |thing| { thing > 2 };
const sum_things = reduce(things, |thing, sum| { sum + thing }, 0);
```

**Comment by SirCmpwn** [comment]
```
const records = sql_query("SELECT * FROM users;");
const names = map records |r| r.name;
const workplace = map records |r| switch r.status {
    Status.employed => r.employer,
    Status.student => r.university
};
```

**Comment by SirCmpwn** [comment]
```
const schools = map(filter(records, |r| r.status == Status.student), |r| r.university)
```

**Comment by andrewrk** [comment]
Where is the memory during all this? Are you expecting these functions to allocate memory? Specifically that last one, with the output of `filter` going to `map`. What is the type of `records` and what is the type of `schools`?

**Comment by SirCmpwn** [comment]
Map is just an example of the usefulness of generalizing |...|. We needn't bikeshed it too much here, we can discuss it separately. And yes, it would allocate memory, and the return type would be []type_of _records, the latter being whatever the SQL API returns.

**Comment by andrewrk** [comment]
This would be the first departure from the design principle that the language does not allocate memory for the programmer. How would you expect the memory to be cleaned up?

**Comment by SirCmpwn** [comment]
defer a free

**Comment by SirCmpwn** [comment]
But like I said, we can discuss map/filter/reduce separately.

**Comment by andrewrk** [comment]
We can discuss it however you want - I'm just trying to understand the whole picture here. It sounds like you're emphasizing that `|args| expression` is something that can be passed where a function pointer is expected. Is that right?

**Comment by SirCmpwn** [comment]
Sure.
