### ISSUE TITLE
Modules, incremental builds, and static linking

### ISSUE THREAD

**Issue by SirCmpwn** [andrewrk/zig#233]
I propose that rather than distribute modules as code and build an entire project in one go, a more traditional approach be considered with independently built objects and libraries. The behavior would be similar to linking with static libraries or object files in C. Each file could then be compiled separately, producing object files to link together within a single module and static libraries to link modules together.

To handle zig's nifty compile time stuff, functions that use compile-time logic could be compiled to emit code rather than to become the compiled functions directly. Then the compiler can invoke them during the build rather than link them normally.

**Comment by thejoshwolfe** [comment]
See also #195

**Comment by SirCmpwn** [comment]
Note that something using shared shared libraries that also include compile-time emitter functions would also probably work, though it'd be pretty lame.

**Comment by SirCmpwn** [comment]
Also, having functions that do stuff at compile time compile to meta-functions that emit code would allow for some crazy shit. You could write a function (in C or Zig) that takes the Zig AST as a parameter and calls API functions to emit code, and then do the aforementioned crazy shit.

**Comment by SirCmpwn** [comment]
For simplicity's sake such functions could probably be designed to emit either Zig or machine code.

**Comment by andrewrk** [comment]
What are the benefits or goals of this approach?

I can think of some downsides:
 * Giving up LTO - you lose the opportunity to optimize across function boundaries of libraries
 * Having to do something complicated like meta functions that emit code

If you're thinking about incremental builds and trying to make compilation faster - we have plans for that. For debug mode, the compiler can automatically break down a given project into .o files or even .so files and then link them together, making subsequent builds take advantage of these cached files. For release mode, you want full optimization, which means we wouldn't settle for pre-built libraries.

I'm also hoping to take [inspiration from Jonathan Blow](https://www.youtube.com/watch?v=14zlJ98gJKA) and make compilation speed so fast that it's not even a big deal to recompile a large project from scratch.

**Comment by SirCmpwn** [comment]
Why do you think you would lose LTO? No reason you can't just serialize whatever data you need to do LTO and stick it in the object files. gcc does this.

>If you're thinking about incremental builds and trying to make compilation faster - we have plans for that. For debug mode, the compiler can automatically break down a given project into .o files or even .so files and then link them together, making subsequent builds take advantage of these cached files. For release mode, you want full optimization, which means we wouldn't settle for pre-built libraries.

Like I said, LTO is totally possible with this design.

>I'm also hoping to take inspiration from Jonathan Blow and make compilation speed so fast that it's not even a big deal to recompile a large project from scratch.

When you can compile 100,000 files in <10 seconds, give me a call.

This is such an important issue that I probably wouldn't use Zig over it. Compiling everything and all of your dependencies from source in one go is a really bad design.

**Comment by andrewrk** [comment]
It's not clear to me what is the bug report or feature request here. A feature request should be of the form:

 * Explain one or more use cases
 * Explain how status quo works with the use case(s) 
 * Explain what could be different than status quo to solve the use case(s) better

I'll re-open if these criteria are met.
