### ISSUE TITLE
Don't overpromise in zig --help, zig targets, etc

### ISSUE THREAD

**Issue by SirCmpwn** [andrewrk/zig#236]
Just add the things that are currently supported and expand it as support is added.

**Comment by andrewrk** [comment]
Huh, interesting. I thought this was working better than it is. Good call.

Was there a particular target that you tried and it didn't work?

**Comment by SirCmpwn** [comment]
freestanding

**Comment by andrewrk** [comment]
what do you think should be the sizes of these types in freestanding?

```
c_short         short               for ABI compatibility with C
c_ushort        unsigned short      for ABI compatibility with C
c_int           int                 for ABI compatibility with C
c_uint          unsigned int        for ABI compatibility with C
c_long          long                for ABI compatibility with C
c_ulong         unsigned long       for ABI compatibility with C
c_longlong      long long           for ABI compatibility with C
c_ulonglong     unsigned long long  for ABI compatibility with C
c_long_double   long double         for ABI compatibility with C
```

**Comment by SirCmpwn** [comment]
That should be derived from the target architecture, not the target OS

**Comment by andrewrk** [comment]
freestanding is now working as expected.

All these targets are in fact supported, at least at one layer:

 * Layer 1 support - can generate machine code for the target. This is true of all of the items in the list of `zig targets`.
 * Layer 2 support - we have standard library support for the target in the OS-specific parts. This is true of x86_64/i386 Linux,MacOS.
