### ISSUE TITLE
volatile memory reading/writing

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#238]
In Clang and LLVM, `volatile` annotates a variable and means that any loads and stores with this variable:

 * Are ordered with respect to other volatile loads and stores
 * Have side effects and thus cannot be optimized out

Zig could follow the pattern of annotating a variable, or we could have a volatile load/store be more explicit with something like:

```zig
fn loadThing(src: &u16) -> u16 {
    return @volatileLoad(src);
}
fn storeThing(dest: &u16, src: &u16) {
    @volatileStore(dest, src);
}
```

If we do this, we might also want to add a compile-time `is_volatile` boolean parameter to the `@memcpy` and `@memset` intrinsics.

Yet another option, is to introduce a `volatile` block, kind of like our `comptime` block:

```zig
fn foo(address: &u16) {
    volatile {
        *address += 1;
    }
}
```

Within the `volatile` block, all memory loads, stores, `@memcpy`, and `@memset` become volatile.

Also note that with the way the syntax works, just like `if` statements you don't need curly braces if you only have 1 expression. So you could do something like `const result = volatile *ptr;`.

To review:

 * Option 1. Annotate variables like C.
 * Option 2. Introduce built-in functions for volatile loads and stores.
 * Option 3. Introduce `volatile` block and loads and stores inside are volatile.

I'm leaning towards option 3.

**Comment by andrewrk** [comment]
Currently our inline assembly syntax uses `volatile` after the word `asm` to indicate that the inline assembly has side effects. With option 3 we could remove this special syntax and say that if inline assembly is inside a volatile block, it has side effects.

**Comment by SirCmpwn** [comment]
+1 for volatile variables

**Comment by andrewrk** [comment]
> +1 for volatile variables

A statement of preference without explanation is not useful.

Here's one reason option 3 is problematic. Let's say we have variables `x` and `framebuffer`. `x` is just some value, but `framebuffer` is memory mapped I/O.

```zig
volatile {
    framebuffer[1234] = x;
}
```

This will work, but it will also mark the load of x as volatile, which is incorrect. So it's hard to avoid accidental volatile usage with this way.

**Comment by andrewrk** [comment]
There's a similar, smaller problem with option 1, which is that if you mark a variable as `volatile`, you might only want volatile stores to it, but loads need not be volatile. So to accurately describe the variable, you would need something like `volatile_read` and `volatile_write`.

**Comment by SirCmpwn** [comment]
```
let foo: volatile &u32; // read/write
let bar: volatile{read} &u32; // read
let baz: volatile{write} &u32; // write
```

or so?

**Comment by SirCmpwn** [comment]
Or you could just make it allways do both and not sweat the small stuff

**Comment by SirCmpwn** [comment]
And volatile should be an attribute of a variable, not a block, just logically speaking.

**Comment by thejoshwolfe** [comment]
> Or you could just make it allways do both and not sweat the small stuff

This goes against Zig's goal of optimality.

> And volatile should be an attribute of a variable, not a block, just logically speaking.

Or perhaps of a pointer instead? Can you give an example of where a volatile local variable makes sense? Like a local var of type u32, for example.

**Comment by SirCmpwn** [comment]
Accessed from multiple threads? Unless you want to make volatile just mean external changes rather than guarantee atomicity.

**Comment by andrewrk** [comment]
volatile means external changes. We have atomics for when you want atomics.

**Comment by SirCmpwn** [comment]
Well, volatile means different things in different languages.

**Comment by thejoshwolfe** [comment]
According to my research, volatile in C does not guarantee order of access. I suggest either the OP be modified to not try to describe C, and/or perhaps we could separate the purposes of the volatile keyword into separate concepts and language features.

**Comment by andrewrk** [comment]
Hmm, maybe instead of C I should say LLVM: http://llvm.org/docs/LangRef.html#volatile-memory-accesses

**Comment by andrewrk** [comment]
Volatile on a pointer makes a lot of sense. And then users could be in control of read/write without explicit syntax, because they could create a volatile pointer and a non volatile pointer at the same time.
