### ISSUE TITLE
block of code as top level declaration

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#255]
Example, static assert:

```zig
const MyType = struct {
    foo: i32,
    bar: f64,
};
{
    assert(@sizeOf(MyType) < 16);
}
```

Zig has order independent Top Level Declarations, so it's not allowed to matter what order zig executes these blocks in. TLD Blocks are run if the file they are inside is imported. TLD Blocks are run in an undefined order. TLD Blocks are allowed inside aggregate types like other TLDs.

**Comment by phase** [comment]
Woud these run on compile time? If on runtime, are they going to be generated in their own functions? Do they run before `main`?

**Comment by andrewrk** [comment]
Yes, these would always run at compile-time.

**Comment by thejoshwolfe** [comment]
How about we answer the runtime vs comptime question in the syntax itself:

```zig
const MyType = struct {
    foo: i32,
    bar: f64,
};
comptime {
    assert(@sizeOf(MyType) < 16);
}
```
