### ISSUE TITLE
arbitrary integer sizes, bit fields, and packed structs

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#261]
Proposal:

`@intType(false, 3)` creates an unsigned integer type with 3 bits. This can be used just like any other integer type. We already have this builtin function, but it currently causes an error to not use one of the common bit counts.

When placed in a normal struct, it gets its own byte and it is addressable.

When placed in an extern struct, it follows the rules of C bit fields depending on the target environment.

When placed in a packed struct, it may or may not be addressable. It will be a compile error if you try to address it and it is not addressable. If placed before other byte-aligned fields, it may cause those fields to no longer be byte-aligned and hence cause them to become unaddressable.

Another reason to have arbitrary integer sizes is that a programmer could do something like:

```
const int = @intType(true, 31);
const Result = struct {
    flag: bool,
    number: int,
}
fn foo() -> Result {
    ...
}
```

Now the return type of function foo could theoretically be a scalar integer instead of a struct, and this optimization could happen in the compiler instead of by the user manually.

**Comment by andrewrk** [comment]
Let's say we have this struct:

```zig
const u1 = @intType(false, 1);
const u2 = @intType(false, 2);
const u3 = @intType(false, 3);

const Data = packed struct {
    a: u3,
    b: u3,
    c: u2,
};
```

Now we have a function:

```
fn foo(data: &const Data) {
    const ptr = &data.b;
    // what is @typeOf(ptr) ?
}
```

I propose that the type looks like this (examples):

 * `&:3 u3`
 * `&:3 const volatile u3`

So the `:3` means, this pointer is 3 bits offset from the byte the pointer points to. The maximum is 7, because if it were 8 then the pointer doesn't have to be a bit offset pointer, and if it were 9 then it should be 1 with the pointer pointing to the next byte.

**Comment by thejoshwolfe** [comment]
can the bit count go arbitrarily high? what arithmetic operations would be allowed for uncommon bit count types?

I've got a concern that perhaps the declarations of `u1`, `u2`, etc would become a hassle for large code bases. I assume that `@intType(false, 1)` would be idempotent accross all files, so you could declare a field with it in one file and a parameter type with it in another file, and the two would be the same type. but would you really want to do that? in your examples you're using aliases that you made, and I imagine most users will want to do the same. furthermore, the name `u1` is the obvious choice for what to name it.

proposal: define builtin types for `u1`..`u7`. these are probably going to be the most common uncommon bit count types used, and it would unify the community to have official definitions and names for them.

are there examples of existing C programs using an uncommon bit count integer larger than a byte?

**Comment by andrewrk** [comment]
> proposal: define builtin types for u1..u7. these are probably going to be the most common uncommon bit count types used, and it would unify the community to have official definitions and names for them.

I think this sounds reasonable.

We could also have in the standard library, something like:

```zig
pub const u1 = @intType(false, 1);
pub const u2 = @intType(false, 2);
pub const u3 = @intType(false, 3);
...
pub const u31 = @intType(false, 31);
pub const u33 = @intType(false, 33);
```

And then in users' code:

```zig
use @import("std").more_int_types;
```

The `use` dumps the types into the current namespace.

We could also do pattern matching on symbol name lookups and resolve any `i\d+` or `u\d+` symbols to automatically resolve to an int type like this.


> are there examples of existing C programs using an uncommon bit count integer larger than a byte?

Here is an example of C code using bitfields with bit count larger than a byte:
https://github.com/Chadderz121/csud/blob/master/include/hcd/dwc/designware20.h#L164

When translated into Zig, this would use uncommon bit count integers since that is how bit fields work in Zig. I'm not aware of it being possible to have uncommon bit count integers as a general type outside of a bit field.

**Comment by andrewrk** [comment]
> can the bit count go arbitrarily high? what arithmetic operations would be allowed for uncommon bit count types?

I think we can make it go arbitrarily high, and we can support all arithmetic operations on all bit count types.
