### ISSUE TITLE
Development build error

### ISSUE THREAD

**Issue by vazub** [andrewrk/zig#263]
**Tested with commit: 786677f80cf7fb34ad8ab45768b910296f9c34cf**
OS: macOS Sierra 10.12.3
LLVM: 3.9.1 (homebrew)
CMake command: 
`$ cmake .. -DCMAKE_INSTALL_PREFIX=$(pwd) -DZIG_LIBC_INCLUDE_DIR=/usr/local/include -DZIG_TEST_COVERAGE=ON`

Getting an error/stop during the build process, as following:
`[ 57%] Building CXX object CMakeFiles/zig.dir/src/ir.cpp.o
/Users/vazub/code/src/github.com/andrewrk/zig/src/ir.cpp:8955:98: error: format specifies type
      'unsigned long long' but the argument has type 'size_t' (aka 'unsigned long') [-Werror,-Wformat]
  ...buf_sprintf("index %" PRIu64 " outside pointer of size %" PRIu64, index, old_size));
                                                            ~~~               ^~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/zig.dir/src/ir.cpp.o] Error 1
make[1]: *** [CMakeFiles/zig.dir/all] Error 2
make: *** [all] Error 2`

**Comment by andrewrk** [comment]
Thanks for the report. Let me know if you run into anything else getting started. Also I'm hanging around in IRC if you have any questions.
