### ISSUE TITLE
add default value for macosx/ios version min

### ISSUE THREAD

**Issue by vazub** [andrewrk/zig#264]
Tested with commit: b1ace32f2373914d92459934b9f0697baca9fe83
OS: macOS Sierra 10.12.3
LLVM: 3.9.1 (homebrew)
CMake command:
$ cmake .. -DCMAKE_INSTALL_PREFIX=$(pwd) -DZIG_LIBC_INCLUDE_DIR=/usr/local/include -DZIG_TEST_COVERAGE=ON

Output:
`Vasyls-MBP:build vazub$ ./run_tests 
Test 1/184 hello world with libc...
Compile failed:
./zig build .tmp_source.zig --export exe --name test --output ./.tmp_exe --release --strip --color on --check-unused --library c
/Users/vazub/code/src/github.com/andrewrk/zig/build/lib/zig/std/darwin.zig:70:24: error: unable to evaluate constant expression
    var buf: [path.len + 1]u8 = undefined;`

**Comment by andrewrk** [comment]
Thanks for the report. I need to get some automated tests going for different OSes and architectures.

**Comment by vazub** [comment]
Just for the sake of not creating another bug with the same name:

Commit: fe3063e58cf81287a26219903f2720439dfeb7e6
> 
> Vasyls-MBP:build vazub$ ./run_tests 
> Test 1/184 hello world with libc...
> Compile failed:
> ./zig build .tmp_source.zig --export exe --name test --output ./.tmp_exe --release --strip --color on --check-unused --library c
> unable to infer -macosx-version-min or -mios-version-min

**Comment by andrewrk** [comment]
I'll make sure this works on my laptop when I get home. But I think you can try setting the `MACOSX_DEPLOYMENT_TARGET` environment variable.

       -mmacosx-version-min=version
       The earliest version of MacOS X that this executable will run on is
       version.  Typical values of version include 10.1, 10.2, and 10.3.9.

       This value can also be set with the MACOSX_DEPLOYMENT_TARGET environment
       variable.  If both the command-line option is specified and the
       environment variable is set, the command-line option will take precedence.

I think we cannot infer this value because you the programmer must decide the minimum macosx version you are targeting. Maybe we could have a default though?

**Comment by vazub** [comment]
> But I think you can try setting the MACOSX_DEPLOYMENT_TARGET environment variable.

That did the trick, all tests passed successfully.

> Maybe we could have a default though?

I concur. The actual version number to use here should be something you are comfortable supporting for the time being, for example - the actual version you use on your home laptop. This should not become the major issue, as anyone will still be possible to override that default value with a command-line option if the need arises.

**Comment by andrewrk** [comment]
Cool, I'll leave the issue open until I do that.
