### ISSUE TITLE
ability to get and set errno when dealing with c

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#274]
errno  is  defined  by  the ISO C standard to be a modifiable lvalue of
       type int, and must not be explicitly declared; errno may  be  a  macro.
       errno  is  thread-local;  setting  it in one thread does not affect its
       value in any other thread.

Based on the way errno is defined here, we cannot rely on it being picked up from a C import, because it can be a macro.

**Comment by thejoshwolfe** [comment]
Couldn't we solve this in userspace?

errno-access.h:

```C
inline static int get_errno() { return errno; }
inline static void set_errno(int value) { errno = value; }
```

and then just include that header file? Or am I missing the point of this, which is that the C-in-Zig parser can't understand what an assignment to errno is supposed to do all the time?

I'm not sure what this issue is really trying to do.

**Comment by andrewrk** [comment]
Hmm, this could actually work. How it would work, is Zig would have to have the ability to render libclang AST into Zig IR and we would do it for static inline functions in .h files. When we use libclang to parse the example above code, it would potentially replace `errno` the macro with normal C code and turn that into normal C AST like everything else.

That requires generating Zig IR from C AST however and we don't have that functionality at the current moment, and probably will not have it before 0.1.0.

This issue is pointing out that currently there is no zig standard library way to access errno, and you also are not guaranteed to get it from `@cImport`.

Your example could be adapted if we created a .h file and a .c file to hide the implementation, and then we have to deal with another .o file, and a C compiler. But we can get/set errno in zig directly by having conditional compilation. With different libcs we can code how to access it, and we know the target libc when compiling, as the `--target-environ` compile variable.

Currently I'm working on a solution that exposes it like this: `@import("std").c._errno()` and the prototype is `fn() -> &c_int`.

The `c` namespace in the standard library would expose libc functions without doing any `@cImport`, and it will be used to do logic like this:

```zig
/// Raises a signal in the current kernel thread, ending its execution.
/// If linking against libc, this calls the abort() libc function. Otherwise
/// it uses the zig standard library implementation.
pub coldcc fn abort() -> unreachable {
    if (linking_libc) {
        c.abort();
    }
    switch (@compileVar("os")) {
        Os.linux => {
            _ = system.raise(system.SIGABRT);
            _ = system.raise(system.SIGKILL);
            while (true) {}
        },
        else => @compileError("Unsupported OS"),
    }
}
```

Likewise the builtin memory allocator will call malloc/realloc/free when linking against libc, and then use the zig standard library implementation when not linking libc.

If we want to have this kind of logic, then we need to be able to check errno without any separate .h or .o file.

**Comment by haberman** [comment]
What is the resolution of this issue? I notice that master has an API `std.os.errno()`:

> To obtain errno, call this function with the return value of the system function call. For some systems this will obtain the value directly from the return code; for others it will use a thread-local errno variable. Therefore, this function only returns a well-defined value when it is called directly after the system function call which one wants to learn the errno value of.

https://ziglang.org/documentation/master/std/#std;os.errno

But it appears that this only works for actual system calls. Many functions in libc return status in `errno` despite not being system calls, eg. `strtof()`. Will there be any way to get `errno` from these functions?

**Comment by Ultra-Code** [comment]
@haberman I don't know why this function isn't anywhere in the documentation but you would need to use `std.c._errno().*` to get the current `errno` value, like andrew showed in the above comment.

**Comment by nevakrien** [comment]
I got error: root struct of file 'os.linux' has no member named 'errno'
and I cant get around it with calling from c which is wild...

**Comment by nektro** [comment]
`extern var errno: c_int;` has worked for me, ymmv

**Comment by nevakrien** [comment]
How do you import code that has errno.h? Because rn I am getting compiler errors with it. 

Which if I am not using errno is fine e but u can have errno.h in some header. Like I can think of some hack c preprocessor tricks but I wans know if there is a "right way"
