### ISSUE TITLE
update syntax for try and nullable unwrapping

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#285]
```zig
try (foo()) |payload| {

} else |err| {

}
test (bar()) |payload| {

} else {

}
fn foo() -> %i32 {
    // ...
}
fn bar() -> ?i32 {
    // ...
}
```

**Comment by raulgrell** [comment]
I like the syntax, it's very consistent with the rest of the language. How would you feel about a finally block in case you want to return from the try/else?

Test seems like a bad name for the null test. Satus quo allows it already:

```
    if ( const payload ?= bar() ) {
        use(payload)
    } else {
        // no payload
    }
```

With #217 we can create an equivalent error-assignment operator

```
    if ( const payload %= foo() ) {
        use(payload)
    } else |err| {
        use(err)
    }
```

The only thing that feels off is the sudden appearence of that |err| in the if statement. I'd also like to be able to do something like iterating through a linked list:

```
    const Node = struct { next: ?&Node };
    var maybe_ptr: ?&Node

    while ( const ptr ?= maybe_ptr ) {
        maybe_ptr = ptr.next
    } else {
         // execute once first time ptr is null, never if breaking out of loop.
    }
```

**Comment by andrewrk** [comment]
> How would you feel about a finally block in case you want to return from the try/else?

How would this work? Wouldn't the finally block be the same as putting an expression after the entire construct?

```zig
try (foo()) |payload| {

} else |err| {

}
// I got your "finally" right here
doSomethingFinally();
```

Another way to write the linked list looping code:

```zig
    while (true) {
        const ptr = maybe_ptr ?? break;
    }
```

**Comment by thejoshwolfe** [comment]
> How would you feel about a finally block in case you want to return from the try/else?

`defer` is intended to generalize and eliminate the need for `finally`.

**Comment by raulgrell** [comment]
> How would this work? Wouldn't the finally block be the same as putting an expression after the entire construct?

Not really, since if you wanted to return from within the blocks, whatever came after the try won't run because the function has returned already. But @thejoshwolfe is right when he says defer generalizes it.

```
fn bar() -> %T {
    defer {
         // Here's my stupid finally block
    }
    try (foo()) |payload| {
        // do something to/with payload
        return payload;
    } else |err| {
        // do something to/with err
        return err
    }
    // or would you not be able to return from a try statement?
    unreachable;
}
```

**Comment by andrewrk** [comment]
> // or would you not be able to return from a try statement?

unlike other languages, there's nothing special about the try block, other than that the `payload` is in scope. The thing that you're "trying" is contained in the parentheses (`foo()` in this case) and that's where you could not return. For example, this would be an error:

```zig
try (return foo) { ... }
```

This would be error: expected error union type, found 'unreachable'.

**Comment by raulgrell** [comment]
In any case, I retract any objections
