### ISSUE TITLE
import segregation

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#3]
* [x] In /my/project/path if I import "std.zig" which is in /usr/lib/zig/lib/std.zig, and then "std.zig" wants to import its own dependencies, those should be looking in the /usr/lib/zig/lib/ root, and not searching /my/project/path.
 * [x] If a.zig imports b.zig and then b.zig imports c.zig, a.zig should not see c.zig symbols.
 * [x] Ability to import into a namespace in addition to importing all. `import a = "a.zig";
 * [x] rename `use` to `import` ?

**Comment by andrewrk** [comment]
```zig
use "a.zig";
```

This would import everything into the global namespace.

```zig
use "a.zig" as a;
```

To use a.zig symbols with this style, use `a::symbol`.

**Comment by thejoshwolfe** [comment]
How about this instead for an explicit namespace:

```
use a = "a.zig";
```

That looks more like you're creating a symbol and initializing it. The `as` syntax you proposed is borrowed from python, which also uses that syntax for its `with` syntax. But for zig, `as` is used for type casting, so it doesn't seem appropriate in this context.

**Comment by andrewrk** [comment]
I like that. It's more consistent with typedef syntax.

```
type foo = other;
```

**Comment by andrewrk** [comment]
`use` was from when I thought to borrow rust syntax. Given the new syntax proposal, how about renaming `use` to `import`?
