### ISSUE TITLE
support more than a fixed number of command line arguments

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#300]
After removing alloca usage, we now have a hard limit of (arbitrarily chosen) 32 command line arguments. More than this will crash startup. The problem is that we get args in the form of `&&u8` and we want to discourage null terminated things, and encourage using slices or situations where the length is known.

There are 2 proposals to solve this:

## Proposal 1: use an API to access command line arguments

A simple program to print all the arguments then becomes:

```zig
const std = @import("std");
const io = std.io;
const Args = std.os.Args;

pub fn main(args: &Args) -> %void {
    var i: usize = 0;
    while (i < args.count(); i += 1) {
        const arg: []const u8 = args.get(i);
        %%io.stdout.printf("{}={}\n", i, arg);
    }
}
```

Alternately, this can be absent from the main function, and command line arguments can be accessed via the standard library directly:

```
const std = @import("std");
const io = std.io;
const os = std.os;

pub fn main() -> %void {
    var i: usize = 0;
    while (i < os.argv.count(); i += 1) {
        const arg: []const u8 = os.argv.get(i);
        %%io.stdout.printf("{}={}\n", i, arg);
    }
}
```

The latter has the benefit that if args are unused, there is no startup cost in code size or processing. In release mode there should really be no code generated to deal with the arguments if unused.

## Proposal 2: use a combination of fixed size buffer and mmap if the count is too large

With this we can retain the current API for main function. If the number of command line arguments is less than some fixed size (32 currently) then we can use the fixed size buffer. Otherwise we request the necessary heap allocation before calling main.

# comparison

Proposal 1 would allow a program that did not look at command line arguments to not generate code to deal with them. Meanwhile proposal 2 would always do a mmap if > N number of args were provided, even if those args are ultimately ignored.

Proposal 1 wastes less memory in the case of a large number of command line args - 8 bytes per argument.

Proposal 1 is easier to implement for every OS, whereas in proposal 2 you have to add specific memory allocation code for every OS. mmap on Posix, HeapAllocate on Windows, etc.

Proposal 1 avoids memory allocation, which some programs may want to do. However, in favor of proposal 2, we could make the max number of command line arguments a compile time variable, and set a flag if more args than this are provided.

Proposal 2 API is cleaner. You can do a `for` loop for example. It will be more familiar to C programmers who expect command line arguments to be passed to main. And it discourages global access of the arguments since they're only available in main and you'd have to capture them to get access to them elsewhere in the program, such as a third party library.

Proposal 2 API lets you do something like the following, that passes leftover args to a child process:

```zig
pub fn main(args: [][]u8) -> %void {    const zig_exe = args[1];
    const leftover_args = args[2...];

    os.ChildProcess.spawn("/usr/bin/foo", leftover_args, ...);
}
```

**Comment by thejoshwolfe** [comment]
my understanding is that the `main(args: &Args)` strategy would be O(1) before main, O(1) for `args.count()`, and O(1) for `args.at(i)`, where O(1) means userspace runtime is not dependent on the number of command line args given to the program. Is all that true for all platforms?

**Comment by andrewrk** [comment]
It's at least true for all platforms when linking libc, since we get `argc: c_int` and `argv: &&u8` from libc main. Probably true for all platforms always.
