### ISSUE TITLE
Proposal: programmatic comptime initialization of arrays

### ISSUE THREAD

**Issue by AndreaOrru** [andrewrk/zig#315]
Example:
```
var array: [64] = undefined;
comptime {
    for (array) |item, index| {
        array[index] = index * index;
    }
}
```
Suggestions on the syntax are welcome, i.e. do we need array to be a `var` if it's only modified at comptime? What if we want it `const` at runtime?

**Comment by andrewrk** [comment]
I think it should look like this:

```zig
const array = {
    var result: [64]usize = undefined;
    for (result) |*item, index| {
        *item = index * index;
    }
    result
};
```

You don't need `comptime` anywhere because everything at global scope is implicitly `comptime`.

I just tried this, found and fixed a bug, and now it works.

**Comment by AndreaOrru** [comment]
This looks beautiful! Thanks.
