### ISSUE TITLE
Fail to build on Debian with packages from apt.llvm.org

### ISSUE THREAD

**Issue by AndreaOrru** [andrewrk/zig#318]
The last commit is supposed to fix the build with the LLVM packages that are shipping with Debian sid by default. However, it causes the build to fail with the packages from apt.llvm.org, that used to work before.

The reason is that they contain a broken `/usr/lib/x86_64-linux-gnu/liblld-4.0.so` symlink (exactly as in the mainstream package, by the way) that takes precedence over the `liblld*` files in the `/usr/lib/llvm-4.0/lib` directory.

```
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/liblld-4.0.so', needed by 'zig'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/zig.dir/all' failed
make[1]: *** [CMakeFiles/zig.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by andrewrk** [comment]
if you remove the packages from sid, does it remove the broken symlink?

**Comment by AndreaOrru** [comment]
Yes the broken symlink is part of the apt.llvm.org packages as well.

**Comment by andrewrk** [comment]
can you try this?

```diff
diff --git a/cmake/Findlld.cmake b/cmake/Findlld.cmake
index 0a30d20..c4bdd89 100644
--- a/cmake/Findlld.cmake
+++ b/cmake/Findlld.cmake
@@ -12,7 +12,7 @@ find_path(LLD_INCLUDE_DIRS NAMES lld/Driver/Driver.h
         /mingw64/include)
 
 find_library(LLD_LIBRARY NAMES lld-4.0 lld PATHS /usr/lib/llvm-4.0/lib)
-if(LLD_LIBRARY)
+if(EXISTS ${LLD_LIBRARY})
     set(LLD_LIBRARIES ${LLD_LIBRARY})
 else()
     macro(FIND_AND_ADD_LLD_LIB _libname_)
```

**Comment by andrewrk** [comment]
Related: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=857653

**Comment by AndreaOrru** [comment]
I confirm it works.

**Comment by AndreaOrru** [comment]
An update on this. The latest packages from sid now work.
