### ISSUE TITLE
implement goto

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#44]
goto has some requirements:
- [x] jumping into a block should be an error
- [x] jumping over a variable declaration, error
- [x] jumping over a defer statement, error
- [x] jumping out of scope should run the defers

**Comment by andrewrk** [comment]
What if you jump backwards over a defer like this?

```zig
label:
defer do_thing();
goto label;
```

**Comment by thejoshwolfe** [comment]
when we branch from the goto, run do_thing() since the defer is going out of scope. then the defer goes right back into scope again.

**Comment by andrewrk** [comment]
If that's the behavior then labels should only be allowed at the start of a block. So it would look like this:

```zig
label: {
    defer do_thing();
    goto label;
}
```

**Comment by andrewrk** [comment]
example of something that should be an error:

```
pub fn foo() {

    goto label;
    const a = undefined;

label:
}
```

Ideally the message would be something like "goto jumps over variable declaration".

**Comment by andrewrk** [comment]
Done with IR branch merge.
