### ISSUE TITLE
integer wrapping

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#46]
* [x] add 'w' variants of integer types which means "wrapping". see code below.
 * [x] fix codegen for non 'w' variants of integers to emit correct nuw/nsw.
 * [x] make pointer arithmetic non wrapping
 * [x] in debug mode, make integer overflow in arithmetic panic. in release mode, undefined behavior.
 * [x] tests for add, sub, mul, shl, negate wrapping crashing
 * [x] tests for add, sub, mul, shl, negate working with wrapping types
 * [x] eval tests for add, sub, mul, shl, negate wrapping cause compile error
 * [x] eval tests for add, sub, mul, shl, negate working with wrapping types
 * [x] when adding normal int to wrapping int, wrapping type takes precedence
 * [x] `@shl_with_overflow` builtin fn

```zig
#max_value(i32) + 1 // undefined behavior. -nuw +nsw
#max_value(u32) + 1 // undefined behavior. +nuw -nsw
#max_value(iw32) + 1 == #min_value(iw32) // -nuw -nsw
#max_value(uw32) + 1 == #min_value(uw32) // -nuw -nsw
```

**Comment by andrewrk** [comment]
we also want "volatile" and perhaps other variable qualifiers. maybe `wrappable` keyword is in order and you can put multiple variable qualifiers in front of the type? instead of iw32, wrappable i32

**Comment by MovingtoMars** [comment]
IMO, there shouldn't be two separate types for wrapping and non-wrapping integers. It would be better to choose a sane default (wrapping) and make it the only option.

**Comment by andrewrk** [comment]
I argue that not wrapping by default is actually safer, less likely to result in bugs, and produces more optimal code. Here's why:

Zig plans to have significantly different debug and release builds. For example, it's planned to have array bounds checking in debug mode but not in release mode. Uninitialized memory is set to all `0xaa` bytes in debug mode, uninitialized in release mode. And finally, in debug mode, all integer arithmetic is checked and the program will crash on overflow. In release mode, overflow is undefined behavior.

Programmers rarely want integers to overflow. By default, we want an overflow to crash the debug build. Only when a programmer explicitly states that they want the wrapping behavior - perhaps they're doing bit fiddling, creating a hash algorithm, or a pseudo random number generator - will they get it. On the other hand, if all integers were wrapping, we wouldn't know if the wrapping was intentional or not, so we couldn't crash the debug build when it accidentally occurred.

As for optimal code, the ability to assume integers will not wrap provides more optimal integer arithmetic.

**Comment by SirCmpwn** [comment]
I suggest using overflow by default (because this is what low level programmers will expect and maps more nicely onto the actual behavior of the CPU), and introducing a checked keyword for checked math. Perhaps something like this:

```
@maxValue(u32) + 1 == @minValue(u32)
checked { @maxValue(u32) + 1 ?? 0 } == 0
```

I personally expect and prefer to have overflow by default, it seems saner to me. Programmers should understand the underlying nature of their integers. Otherwise, I would prefer something like `unchecked { ... }` over the ugly macros.

**Comment by thejoshwolfe** [comment]
see #159 for the current state of this feature.
