### ISSUE TITLE
for loop

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#51]
* [x] for loop which can iterate over array with optional index
 * [ ] ~~for loop which can iterate over a range~~ see #139
 * [x] `continue` for for loop
 * [x] `|item, index| expr` syntax to match %% operator
 * [ ] make the item variable optional
 * [x] `|*item|` so you can assign to it

**Comment by andrewrk** [comment]
New plan:

```zig
fn f(array: []u8) {
    for (value in array) {
        // #typeof(value) is u8
        // cannot assign to value
    }
}

fn f(array: []BigOleStruct) {
    for (*value in array) {
        // #typeof(value) is &BigOleStruct
        // cannot assign to value, but can deference value
    }
}

fn numeric_for_loop() {
    for (index : u32 in 0...10) {

    }
}

fn numeric_for_loop() {
    for (index : u32 in 10...0) {
        print_str("hi\n"); // error: unreachable code
    }
}
```

**Comment by andrewrk** [comment]
New proposal, instead of introducing an `in` keyword, make it look like function invocation syntax, and then index can look like an optional last argument:

```zig
fn f(array: []u8) {
    for (value, array) {
        // @typeof(value) is u8
        // cannot assign to value
    }

    for (value, array, index) {
    }
}

fn numeric_for_loop() {
    for (index : u32, 0...10) {

    }
}
```

**Comment by phase** [comment]
>  for loop which can iterate over a range

Why not make ranges just create a new array? That would be great here and in other scenarios.

```
const exclusiveRange: []u32 = 5...10; //5-9, excludes 10
const inclusiveRange: []u32 = 5..10; //5-10, includes 10
for (index: u32, inclusiveRange) {
    for (otherIndex: u32, 7..12) {
    }
}

// including variables in ranges would be sweet
const a : u32 = 5;
const b : u32 = 17;
const r : []u32 = a..b; //5-17
```

**Comment by andrewrk** [comment]
This idea is elegant, but let me throw a couple of monkey wrenches your way:

```zig
const a : u32 = 5;
const b : u32 = 17;
const r : []u32 = a..b; //5-17
```

In this example, a and b happen to be known at compile time, so this could turn into a compile time fixed size array `[13]u32`. In fact, since `r` is declared `const`, it can be pulled out of the function and into the global memory area (as if it were declared `static` in C).

However let's say that these things are not the case, and it looked like this:

```zig
fn f(a : u32, b : u32) => {
    const r : []u32 = a..b;
}
```

Now we have a problem. The memory has to exist somewhere, and zig, like C, never allocates or deallocates memory - that functionality will be provided by optional standard library functions.

So the memory for the array would have to be allocated on the stack, at runtime, which is problematic because you might run out of stack space, and if `a` or `b` could be controlled by a user, you would certainly not want to give the user control of how much memory you allocate on the stack.

And then:

```zig
for (otherIndex: u32, 7..12) {
}
```

This has the same memory allocation problem. Let's say it was 7...100000000. Here it is unacceptable for the compiler to *actually* generate an array. Clearly the programmer just wants the index to iterate between the ranges. In fact you would want the compiler to generate an error if that optimization was not going to occur.

**Comment by hrasdt** [comment]
> This has the same memory allocation problem. Let's say it was 7...100000000. Here it is unacceptable for the compiler to actually generate an array. Clearly the programmer just wants the index to iterate between the ranges. In fact you would want the compiler to generate an error if that optimization was not going to occur.

This is probably totally irrelevant, but Python solves this by having `range(x)` return a [generator](https://wiki.python.org/moin/Generators), rather than an allocated array. When you're iterating over it, it looks like an array, but in reality, it's just a function that returns a new value every time you call it.
