### ISSUE TITLE
maybe type

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#7]
* [x] generic `?` syntax for declaring a maybe type
 * [x] syntax for assigning the maybe state to a maybe type
 * [x] if (const foo ?= expression) {} syntax
 * [x] `??` unwrapping expression
 * [x] test for many `?` qualifiers on a type
 * [x] optimization for bool - use 0 for false, 1 for true, 2 for maybe state
 * [x] optimization for pointer - use null pointer for maybe state
 * [x] error for if var expression initializer not maybe type

**Comment by andrewrk** [comment]
Better idea, no null pointer constant.

Instead we have a "maybe" type, perhaps by putting a question mark before another type, like this:

`?*mut u8`

This represents a tagged union which can either be `None` or a `*mut u8` which is guaranteed to not be null. You could `.unwrap()` on a maybe type to resolve to a non-null type, or panic.

Also, a `??` operator which the left operand is a maybe type and the right operand is an expression which is of the unwrapped type. So you could for example:

```zig
fn func(x : ?bool) {
    let want_the_thing = x ?? true;
}
```

Now you have an optional boolean that has a default value of true.

Or:

```zig
fn create_a_thing() -> error {
    let thing = malloc(...) ?? {
        return Error.OutOfMem;
    };
    things.append(thing);
    return Error.None;
}
```

The right hand side of the `??` returned unreachable which is also legal.

**Comment by thejoshwolfe** [comment]
Alternate unpacking syntax ideas:

idea 1:

```
fn report_error(msg : string, maybe_additional_info : ?string) {
    report(str);
    ifunpack additional_info = maybe_additional_info {
        report(additional_info);
    }
}
```

idea 2:

```
fn report_error(msg : string, maybe_additional_info : ?string) {
    report(str);
    if let additional_info ?= maybe_additional_info {
        report(additional_info);
    }
}
```
