### ISSUE TITLE
cmake/Findclang.cmake uses hardcoded paths

### ISSUE THREAD

**Issue by kiljacken** [andrewrk/zig#70]
This causes compilation to fail on setups without clang/llvm 3.7 and on setups with those, if they have been installed to another location.

**Comment by andrewrk** [comment]
It doesn't have hard coded paths. It looks in a place appropriate for your system. The hardcoded paths you see there are hints that cmake will use if the default logic fails.

**Comment by andrewrk** [comment]
I'm going to close this since I completely deleted the dependency on libclang. We'll need to figure this out eventually though. Maybe I can try getting it working on fedora myself in a vm and make sure the findclang cmake script will succeed.
