### ISSUE TITLE
ability to cast isize to pointer

### ISSUE THREAD

**Issue by MovingtoMars** [andrewrk/zig#91]
I need to be able to do this to implement `malloc`, in order to cast the result from the `mmap` syscall to a memory location.

**Comment by thejoshwolfe** [comment]
`void` is a special type in zig. in C, `void` is a keyword that means lots of things. if you want a pointer to untyped memory, just use `&u8`. it looks like you found a bug in the compiler where `&void` is not implemented yet, but the plan is to make `void`, `&void`, `&&void`, etc. all 0-bit types, meaning they get deleted before code gen. this is more true to the meaning of "void" and i think it would make more sense to everyone anyway if C hadn't overused "void" so confusingly.

**Comment by andrewrk** [comment]
I think you can cast isize to &u8

**Comment by MovingtoMars** [comment]
Ok then. It just doesn't really make sense that `&void` is a 0-bit type. If `void` is a 0-bit type, then `&void` should be a pointer to a 0-bit type.

**Comment by andrewrk** [comment]
nope, looks like I need to add an explicit cast from isize to pointer.

However let's talk about the malloc implementation on IRC, I think we actually might need generics (see #22) for the signature of malloc:

```zig
pub fn malloc(inline T: type, count: isize) -> []T {
    // ...
}
```

**Comment by andrewrk** [comment]
> Ok then. It just doesn't really make sense that &void is a 0-bit type. If void is a 0-bit type, then &void should be a pointer to a 0-bit type.

`&void` is in fact a pointer to a 0-bit type, and pointers to 0-bit types are themselves a 0-bit type.
